name: "Fetch github-package latest snapshot version"
inputs:
  org:
    description: "github Organization"
    required: true
  packageType:
    description: "package manager name"
    required: true
  packageName:
    description: "package name"
    required: true
  ghToken:
    description: "GitHub access token. specify `secrets.GITHUB_TOKEN`"
    required: false
outputs:
  version:
    description: "latest snapshot version"
runs:
  using: "node20"
  main: "dist/index.js"
