name: test

on:
  workflow_dispatch:
  push:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Fetch latest SNAPSHOT version from GitHub Packages
      id: liquibase-core-latest-snapshot-version
      uses: momosetkn/fetch-gh-package-latest-snapshot-version@main
      with:
        org: liquibase
        packageType: maven
        packageName: org.liquibase.liquibase-core
        githubToken: ${{ secrets.GITHUB_TOKEN }}

    - name: Test with latest liquibase SNAPSHOT version
      run: |
        ./gradlew test -PliquibaseVersion=${{ steps.liquibase-core-latest-snapshot-version.outputs.version }}
